# This is the buildconfig for building our `HelloTransparentRelease` binary.

# We want to build a binary with sources from this repo:
repo = "https://github.com/project-oak/hello-transparent-release"

# To build the `HelloTransparentRelease` binary we check out the repo from this commit
# (note to self: update, if a commit changes the builder Docker image):
commit_hash= "57cc56ba78c24802f449b7e7ffce1a583f8f0a91"

# To build the `HelloTransparentRelease` binary we use this builder Docker image:
builder_image="gcr.io/oak-ci/oak:hello-transparent-release"

# To build `HelloTransparentRelease` binary with the builder Docker image we use the command:
command = ["./scripts/build_from_docker"]

# Our builder Docker image writes the `HelloTransparentRelease` binary to this output path:
output_path =  "./out/HelloTransparentRelease"

