# This is the buildconfig for building our `HelloTransparentRelease` binary.

# We want to build a binary with sources from this repo:
repo = "https://github.com/project-oak/hello-transparent-release"

# To build the `HelloTransparentRelease` binary we check out the repo from this commit
# (note to self: update, if a commit changes the builder Docker image):
commit_hash= "20ff5d888ba2ce4512a3898812786dde8351f1de"

# To build the `HelloTransparentRelease` binary we use this builder Docker image:
builder_image="gcr.io/oak-ci/hello-transparent-release@sha256:eb0297df0a4df8621837369006421dd972cc3e68e6da94625539f669d49f1525"

# To build `HelloTransparentRelease` binary with the builder Docker image we use the command:
command = ["./scripts/build_from_docker"]

# Our builder Docker image writes the `HelloTransparentRelease` binary to this output path:
output_path =  "./out/HelloTransparentRelease"

