# This is the buildconfig for building the `HelloTransparentRelease` binary.

# We want to build a binary with sources from this repo:
repo = "https://github.com/project-oak/hello-transparent-release"

# To build the `HelloTransparentRelease` binary we check out the repo from the commit with:
# (usually, we'll just pick the latest one)
commit_hash= "d97c8b0efd6279522b2a318cc52cd142805a606c"

# To build the `HelloTransparentRelease` binary we use this builder Docker image:
builder_image="europe-west2-docker.pkg.dev/oak-ci/hello-transparent-release/hello-transparent-release@sha256:eb0297df0a4df8621837369006421dd972cc3e68e6da94625539f669d49f1525"

# To build `HelloTransparentRelease` binary with the builder Docker image we use the command:
command = ["./scripts/build"]

# The builder Docker image writes the `HelloTransparentRelease` binary to this relative output_path:
output_path =  "./out/HelloTransparentRelease"
